name: Check Reactions on Pr and Issue
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Reactions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
            | jq '.[] | {number: .number, title: .title, reactions: .reactions}'