name: Check Reactions on Pr and Issue
on:
  schedule:
    - cron: "0 0 * * 0" # Run at midnight on Sundays
  workflow_dispatch: {} # Allow manual triggering
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Reactions
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({ auth: '${{ secrets.GITHUB_TOKEN }}'});
            const { owner, repo } = context.repo;
            // Check issues with more than 5 reactions
            const issuesResponse = await octokit.issues.listForRepo({
              owner,
              repo,
              state: 'open',
            });
            if (issuesResponse.data) {
              console.log(`Found ${issuesResponse.data.length} issues`);
              for (const issue of issuesResponse.data) {
                console.log(`Checking issue #${issue.number}`);
                if (issue.reactions && issue.reactions.total_count > 5) {
                  console.log(`Issue #${issue.number} has ${issue.reactions.total_count} reactions`);
                  await octokit.issues.addLabels({
                    owner,
                    repo,
                    issue_number: issue.number,
                    labels: ['more than 5 reactions'],
                  });
                }
              }
            }

            // Check pull requests with more than 5 reactions
            const pullsResponse = await octokit.pulls.list({
              owner,
              repo,
              state: 'open',
            });
            if (pullsResponse.data) {
              console.log(`Found ${pullsResponse.data.length} pull requests`);
              for (const pull of pullsResponse.data) {
                console.log(`Checking pull request #${pull.number}`);
                if (pull.reactions && pull.reactions.total_count > 5) {
                  console.log(`Pull request #${pull.number} has ${pull.reactions.total_count} reactions`);
                  await octokit.issues.addLabels({
                    owner,
                    repo,
                    issue_number: pull.number,
                    labels: ['more than 5 reactions'],
                  });
                }
              }
            }
