name: Check Reactions on Pr and Issue
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  schedule:
    - cron: "0 0 * * 0" # Run at midnight on Sundays
  workflow_dispatch: {} # Allow manual triggering
jobs:
  check-reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Reactions
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;

            // Check issues with more than 5 reactions
            const issuesResponse = await github.issues.listForRepo({
              owner,
              repo,
              state: 'all',
            });
            if (issuesResponse.data) {
              console.log(`Found ${issuesResponse.data.length} issues`);
              for (const issue of issuesResponse.data) {
                console.log(`Checking issue #${issue.number}`);
                const labelsResponse = await github.issues.listLabelsOnIssue({
                  owner,
                  repo,
                  issue_number: issue.number,
                });
                const labels = labelsResponse.data.map((label) => label.name);
                if (issue.reactions && issue.reactions.total_count > 5 && !labels.includes('more than 5 reactions')) {
                  console.log(`Issue #${issue.number} has ${issue.reactions.total_count} reactions`);
                  await github.issues.addLabels({
                    owner,
                    repo,
                    issue_number: issue.number,
                    labels: ['more than 5 reactions'],
                  });
                }
              }
            }

            // Check pull requests with more than 5 reactions
            const pullsResponse = await github.pulls.list({
              owner,
              repo,
              state: 'all',
            });
            if (pullsResponse.data) {
              console.log(`Found ${pullsResponse.data.length} pull requests`);
              for (const pull of pullsResponse.data) {
                console.log(`Checking pull request #${pull.number}`);
                const labelsResponse = await github.issues.listLabelsOnIssue({
                  owner,
                  repo,
                  issue_number: pull.number,
                });
                const labels = labelsResponse.data.map((label) => label.name);
                if (pull.reactions && pull.reactions.total_count > 5 && !labels.includes('more than 5 reactions')) {
                  console.log(`Pull request #${pull.number} has ${pull.reactions.total_count} reactions`);
                  await github.issues.addLabels({
                    owner,
                    repo,
                    issue_number: pull.number,
                    labels: ['more than 5 reactions'],
                  });
                }
              }
            }
